#!/bin/sh

GDBSERVER_USER_REMOTE="root"
GDBSERVER_PATH_REMOTE="/home"
GDBSERVER_EXECUTABLE="${GDBSERVER_PATH_REMOTE}/$(basename $1)"
GDBSERVER_TARGET_HOST="${2}"
GDBSERVER_TARGET_PORT="${3}"
NFS_TARGET_PATH="{{ develop.target.nfsroot }}${GDBSERVER_PATH_REMOTE}"

cp -v "${1}" "${NFS_TARGET_PATH}"

ssh -L"${GDBSERVER_TARGET_PORT}:localhost:${GDBSERVER_TARGET_PORT}" "${GDBSERVER_USER_REMOTE}@${GDBSERVER_TARGET_HOST}" << EOF
cd "${GDBSERVER_PATH_REMOTE}"
killall gdbserver 2>/dev/null
export LD_LIBRARY_PATH="${GDBSERVER_PATH_REMOTE}"
gdbserver --once :"${GDBSERVER_TARGET_PORT}" "${GDBSERVER_EXECUTABLE}"
EOF
